"""
Django settings for cocinita project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-vvp)peja#)ffq_)ib-#r%xuia!1(gq1a*w9q%mtnp#t@fp96p0'
DEBUG = True   # ⚠️ En producción ponelo en False

# 🔹 Tu dominio en PythonAnywhere
ALLOWED_HOSTS = ['*']


# Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  
    'rest_framework',
    'rest_framework.authtoken',
     'rest_framework_simplejwt',
    'myapp',
    'login_jefe',
    'login_ventas',
    "corsheaders",


]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [

    "https://48p82xms-8002.brs.devtunnels.ms",
    "http://localhost:5173",
    'http://127.0.0.1:8002',


]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'cocinita.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # opcional si usás templates globales
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cocinita.wsgi.application'

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        # El nombre del archivo donde se guardará la base de datos.
#        # BASE_DIR es una variable de Django que apunta a la raíz del proyecto.
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
     'default': { 
         'ENGINE': 'django.db.backends.mysql', 
        
         'NAME': 'cocina', 
        
         'USER': 'cristian', 
         'PASSWORD': 'patomalo666',
         'HOST': '127.0.0.1',
         'PORT': '3306',
        
         # Opcional, pero recomendado:
         'OPTIONS': {
             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
         }
     }
 }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'es'       # idioma español
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True
DATE_FORMAT = 'd/m/Y'          # día/mes/año
TIME_FORMAT = 'H:i'            # hora 24h
DATETIME_FORMAT = 'd/m/Y H:i'  # fecha + hora
LOGIN_URL = '/login/'

# 🔹 Archivos estáticos
# 🔹 Archivos estáticos
STATIC_URL = '/myapp/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'