# Generated by Django 5.2.4 on 2025-07-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_isla'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslaPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islas_premium', to='myapp.cliente')),
            ],
        ),
    ]
