# Generated by Django 5.2.4 on 2025-11-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccionfindefiesta',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
