# Generated by Django 5.2.4 on 2025-11-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_boutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='horario_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
