# Generated by Django 5.2.4 on 2025-08-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cantidad_recepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidades', to='myapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='myapp.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Cantidad',
        ),
        migrations.DeleteModel(
            name='Recepcion',
        ),
    ]
