# Generated by Django 5.2.4 on 2025-08-15 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cantidades_recepcionn_delete_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleccionRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion', to='myapp.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Recepcionn',
        ),
    ]
