# Generated by Django 5.2.4 on 2025-09-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarraTragos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra_tragos', to='myapp.cliente')),
            ],
        ),
    ]
