# Generated by Django 5.2.4 on 2025-09-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_barratragos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion_Platos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato_principal', models.TextField(blank=True, null=True)),
                ('plato_infantil', models.TextField(blank=True, null=True)),
                ('aclaraciones_alimentarias', models.TextField(blank=True, null=True)),
                ('num_adultos', models.PositiveIntegerField(blank=True, null=True)),
                ('num_ninos', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elecciones', to='myapp.cliente')),
            ],
        ),
    ]
